42LTeam/pong

front/src/components/svg/ChatIcon.tsx, front/src/components/svg/LeaderboardIcon.tsx, front/src/components/svg/PlayIcon.tsx, front/src/containers/header/NavigationBubble.tsx, front/src/css/header.css
renamed components "Button" that were more "Icon"
=> fix header navigation icons and css

back/src/client/client.gateway.ts, back/src/message/message.service.ts, front/src/components/svg/Cross.tsx, front/src/components/utils/Notification.tsx, front/src/containers/Application.tsx, front/src/containers/Auth.tsx, front/src/containers/header/UserBubble.tsx, front/src/containers/leaderboardpage/LeaderboardPage.tsx, front/src/containers/leaderboardpage/LeaderboardPlaceBubble.tsx, front/src/containers/leaderboardpage/LeaderboardTabs.tsx, front/src/containers/settingspage/Settings.tsx, front/src/containers/settingspage/UserSettings.tsx, front/src/containers/social/SocialBody.tsx, front/src/containers/social/chat/Chat.tsx, front/src/containers/social/conversation/Conversations.tsx, front/src/containers/social/conversation/NewMessagePopup.tsx, front/src/containers/social/friend/FriendList.tsx, front/src/containers/social/friend/Friends.tsx, front/src/css/main.css, front/src/css/notification.css
Ajout d'un systeme de notifications et changement de la gestions des chat
=> 26 front websocket notification

back/src/auth/auth.controller.ts, back/src/main.ts, front/src/api.ts, front/src/containers/Auth.tsx
with   const localhostfront = process.env.LOCALHOST ? process.env.LOCALHOST + ':5173' : 'http://localhost:5173';
=> Patching localhost hardcode 

back/src/auth/auth.controller.ts, back/src/main.ts, front/src/api.ts, front/src/containers/Auth.tsx
J'ai fix l'authentification, il faut par contre changer le .env
Je l'ai envoyer sur ressources
=> fixed auth

back/src/channel/channel.module.ts, back/src/channel/channel.service.ts, back/src/channel/controllers/channel.controller.ts, back/src/channel/controllers/conversation.controller.ts
J'ai laisser un TODO pour le faire plus tard j'ai besoin d'Edouardo pour checker un bail
=> 47 back conversation endpoint creation

back/src/channel/channel.controller.ts, back/src/channel/channel.service.ts, back/src/user/user.service.ts, front/src/api.ts, front/src/components/friend/Friend.tsx, front/src/components/utils/Button.tsx, front/src/components/utils/ContextMenu.tsx, front/src/components/utils/PopUp.tsx, front/src/containers/social/friend/FriendList.tsx, front/src/css/notification.css
J'ai ajouter un component context menu, tu peux mettre des trucs dedans et quand tu fais click droit sur ces trucs ca ouvre un menu custom
=> 43 front right click on some elements

back/src/friend/friend.service.ts, front/src/api.ts, front/src/containers/social/conversation/NewMessagePopup.tsx, front/src/containers/social/friend/Friends.tsx, front/src/css/notification.css
=> All users in pravate message available

back/prisma/schema.prisma, back/src/channel/channel.module.ts, back/src/channel/channel.service.ts, back/src/client/client.gateway.ts, back/src/message/message.controller.ts, back/src/message/message.service.ts, front/src/api.ts, front/src/components/conversation/Conversation.tsx, front/src/containers/Application.tsx, front/src/containers/social/chat/Chat.tsx, front/src/containers/social/conversation/Conversations.tsx, front/src/containers/social/conversation/NewMessagePopup.tsx, front/src/containers/social/friend/Friends.tsx
=> 49 back rajouter un lastread à userchanel

back/src/friend/friend.module.ts, back/src/match/match.module.ts, back/src/match/match.service.ts, back/src/user/user.controller.ts, back/src/user/user.module.ts, back/src/user/user.service.ts
J'ai encore plus peur du back mtn ct l'enfer :o
=> add of an endpoint to get all userMatch[] of an user by its ID

back/src/user/user.controller.ts, back/src/user/user.service.ts, front/src/api.ts, front/src/components/friend/Friend.tsx, front/src/components/utils/Removable.tsx, front/src/containers/social/conversation/NewMessagePopup.tsx, front/src/containers/social/friend/AddFriend.tsx, front/src/css/popup.css
Je suis plutot content du resultat. Dans l'ideal faudrait faire un component suggestions car on a deux fois le mechanisme de suggestions une fois dans popup et une fois dans addfriend. Je vais reflechir a comment en faire un component mais ca sera une autre issue
=> 59 addfriend the sequel

front/src/containers/social/conversation/NewMessagePopup.tsx, front/src/containers/social/friend/AddFriend.tsx
=> fixed suggestions on popup and addfriend

back/src/client/client.module.ts, back/src/client/gateways/game.gateway.ts, back/src/client/gateways/game/Game.class.ts, back/src/client/gateways/game/GameBall.class.ts, back/src/client/gateways/game/GameEngine.class.ts, back/src/client/gateways/game/GamePlayer.class.ts, front/src/containers/gamepage/GamePage.tsx
Add multiple games, DB push.
Bug fixes
=> 76 back continue pong game

back/src/channel/channel.service.ts, back/src/channel/controllers/channel.controller.ts, back/src/client/gateways/client.gateway.ts
Service and controller for removing a user from a channel in the back
=> add service and controller for removing user from a channel

back/src/user/pipes/userIdValid.pipe.ts, back/src/user/user.controller.ts
J'ai rajouté un pipe de validation, et je l'ai mis pour tout les controllers qui utilisent un userId.
Ça renvoi un joli message d'erreur du coup.
=> 103 backget usersid666

back/src/user/user.controller.ts
Error fixed : Le userIdValidation était avant le ParsIntPipe, du coup c'était pas un number qu'il recevait. Je les ai changés de place et j'ai checker les autres aussi.
=> error fixed

back/src/app.module.ts, back/src/auth/auth.controller.ts, back/src/auth/auth.module.ts, back/src/block/block.controller.ts, back/src/block/block.module.ts, back/src/block/block.service.ts, back/src/message/message.service.ts, front/src/api.ts, front/src/components/chat/Message.tsx, front/src/components/conversation/Conversation.tsx, front/src/components/friend/Friend.tsx, front/src/components/utils/Avatar.tsx, front/src/containers/Application.tsx, front/src/containers/Auth.tsx, front/src/containers/HomePage/HomePage.tsx, front/src/containers/social/SocialBody.tsx, front/src/containers/social/channel/ChannelMembersList.tsx, front/src/containers/social/chat/Chat.tsx, front/src/containers/social/conversation/Conversations.tsx, front/src/containers/social/conversation/NewMessagePopup.tsx, front/src/containers/social/friend/AddFriend.tsx, front/src/containers/social/friend/FriendList.tsx, front/src/containers/social/friend/Friends.tsx
=> 77 frontback block and unblock users

front/src/containers/Application.tsx, front/src/containers/NotFound.tsx, front/src/containers/profilepage/ProfilePage.tsx, front/src/css/main.css
=> added 404Page that works for general urls and ProfilePage

back/src/channel/channel.service.ts, back/src/channel/controllers/channel.controller.ts, front/src/api.ts, front/src/components/friend/Friend.tsx, front/src/components/svg/Lock.tsx, front/src/components/utils/TextInput.tsx, front/src/containers/social/conversation/Conversations.tsx, front/src/containers/social/conversation/EditChannelPopOver.tsx, front/src/containers/social/conversation/NewMessagePopup.tsx, front/src/css/popup.css
Tout est dans le titre un admin peut faire click droit sur le channel et au dessus de leave t;auras modifier le salon
=> 157 edit channel

back/Dockerfile, back/package.json, front/src/containers/settingspage/Settings.tsx
=> upload avatar is back + fixes

back/src/user/user.service.ts
=> Add #userId for username at account creation and at change username call

nginx/nginx.conf
=> deacticate indexing of folder uploads

front/src/containers/Auth.tsx
=> Deconnect is possible

back/package-lock.json, back/package.json, back/src/file-upload/file-upload.service.ts, back/src/user/user.controller.ts, front/src/api.ts, front/src/containers/settingspage/Settings.tsx
Checks are good, no strange file input
=> 195 backfront verify image file type

.gitignore, back/Dockerfile, back/package-lock.json, front/src/containers/social/conversation/EditChannelPopOver.tsx
=> 203 front password sur un chan privé ne sert à rien
